PYTHONPATH=. accelerate launch --num_processes 3 --main_process_port 29500 LaMed/src/train/amos_train.py \
    --version v0 \
    --model_name_or_path microsoft/Phi-3-mini-4k-instruct \
    --cache_dir /datasets/mohammed/amosmm/cache \
    --model_type phi3 \
    --lora_enable False \
    --freeze_llm True \
    --lora_r 16 \
    --vision_tower vit3d \
    --bf16 True \
    --output_dir /home/jma/datasets/mohammed/amosmm/models/triplet \
    --triplet True \
    --pretrain_vision_model /home/jma/datasets/mohammed/amosmm/models/pretrained_ViT.bin \
    --num_train_epochs 200 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --do_eval False \
    --eval_accumulation_steps 1 \
    --eval_steps 0.99 \
    --save_strategy "steps" \
    --save_steps 20000 \
    --save_total_limit 1 \
    --learning_rate 5e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 0.001 \
    --gradient_checkpointing False \
    --dataloader_pin_memory True \
    --dataloader_num_workers 4 \
    --report_to none \
    --prompt "simple" \
    --task mrg \
    --json_path Data/AMOSMM.json \
    --with_template True \
    --image_size "32, 256, 256" \
    --model_max_length 768

PYTHONPATH=. accelerate launch --num_processes 1 --main_process_port 29500 LaMed/src/train/amos_train.py \
    --version v0 \
    --model_name_or_path microsoft/Phi-3-mini-4k-instruct \
    --cache_dir /datasets/mohammed/amosmm/cache \
    --model_type phi3 \
    --lora_enable False \
    --freeze_llm True \
    --lora_r 16 \
    --vision_tower vit3d \
    --bf16 True \
    --output_dir /home/jma/datasets/mohammed/amosmm/models/phi3 \
    --pretrain_vision_model /home/jma/datasets/mohammed/amosmm/models/pretrained_ViT.bin \
    --num_train_epochs 150 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --do_eval False \
    --eval_accumulation_steps 1 \
    --eval_steps 0.99 \
    --save_strategy "steps" \
    --save_steps 20000 \
    --save_total_limit 1 \
    --learning_rate 5e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 0.001 \
    --gradient_checkpointing False \
    --dataloader_pin_memory True \
    --dataloader_num_workers 4 \
    --report_to none \
    --prompt "simple" \
    --task mrg \
    --json_path Data/AMOSMM.json \
    --with_template True \
    --image_size "32, 256, 256" \
    --model_max_length 768